import { afterEach, describe, expect, it } from 'vitest';
import { claudeContent } from './content';

const mcpServerUrl = 'https://learn.microsoft.com/api/mcp';

function toolUse(id: string, name: string, overrides: object = {}) {
  return {
    type: 'tool_use',
    id,
    name: `microsoft-learn:${name}`,
    input: { query: 'private query' },
    integration_name: 'microsoft-learn',
    mcp_server_url: mcpServerUrl,
    ...overrides,
  };
}

function toolResult(toolUseId: string) {
  return {
    type: 'tool_result',
    tool_use_id: toolUseId,
    content: [{ type: 'text', text: 'private result' }],
  };
}

function renderTurn(message: object, conversationUuid = 'conversation-1') {
  document.body.innerHTML = `
    <div data-testid="transcript-row">
      <div data-is-streaming="false">
        <div data-testid="TurnStatus"></div>
      </div>
    </div>
  `;
  const status = document.querySelector('[data-testid="TurnStatus"]');
  const turn = document.querySelector<HTMLElement>(claudeContent.turnSelector);
  if (!status || !turn) {
    throw new Error('Expected the fixture turn.');
  }

  Object.defineProperty(status, '__reactFiber$test', {
    configurable: true,
    value: {
      memoizedProps: { 'data-testid': 'TurnStatus' },
      return: {
        memoizedProps: { blocks: [] },
        return: {
          memoizedProps: { message, conversationUuid },
          return: null,
        },
      },
    },
  });
  return turn;
}

const now = () => new Date('2026-09-11T12:00:00.000Z');

describe('Claude tool call detector', () => {
  afterEach(() => {
    document.body.replaceChildren();
  });

  it('reads completed MCP tool calls without reading their payloads', () => {
    const turn = renderTurn({
      uuid: 'assistant-1',
      content: [
        toolUse('toolu_1', 'microsoft_docs_search'),
        toolResult('toolu_1'),
        { type: 'text', text: 'private answer' },
        toolUse('toolu_2', 'microsoft_docs_fetch'),
        toolResult('toolu_2'),
      ],
    });

    const calls = claudeContent.readToolCalls(
      turn,
      new Set(['assistant-1']),
      now,
    );

    expect(calls).toEqual([
      {
        site: 'claude',
        id: 'toolu_1',
        conversationId: 'conversation-1',
        turnId: 'assistant-1',
        appName: 'microsoft-learn',
        toolName: 'microsoft_docs_search',
        toolIndex: 1,
        detectedAt: '2026-09-11T12:00:00.000Z',
      },
      {
        site: 'claude',
        id: 'toolu_2',
        conversationId: 'conversation-1',
        turnId: 'assistant-1',
        appName: 'microsoft-learn',
        toolName: 'microsoft_docs_fetch',
        toolIndex: 2,
        detectedAt: '2026-09-11T12:00:00.000Z',
      },
    ]);
    expect(JSON.stringify(calls)).not.toContain('private');
  });

  it('ignores messages not generated by a request observed live', () => {
    const turn = renderTurn({
      uuid: 'history-1',
      content: [
        toolUse('toolu_1', 'microsoft_docs_search'),
        toolResult('toolu_1'),
      ],
    });

    expect(
      claudeContent.readToolCalls(turn, new Set(['assistant-1']), now),
    ).toEqual([]);
  });

  it('ignores built-in tools and calls still waiting for a result', () => {
    const turn = renderTurn({
      uuid: 'assistant-1',
      content: [
        toolUse('toolu_1', 'web_search', {
          name: 'web_search',
          integration_name: null,
          mcp_server_url: null,
        }),
        toolResult('toolu_1'),
        toolUse('toolu_2', 'web_fetch', {
          name: 'web_fetch',
          integration_name: 'Web Fetch',
          mcp_server_url: null,
        }),
        toolResult('toolu_2'),
        toolUse('toolu_3', 'microsoft_docs_fetch'),
      ],
    });

    expect(
      claudeContent.readToolCalls(turn, new Set(['assistant-1']), now),
    ).toEqual([]);
  });

  it('keeps a tool name that has no integration prefix', () => {
    const turn = renderTurn({
      uuid: 'assistant-1',
      content: [
        toolUse('toolu_1', 'search', { name: 'search' }),
        toolResult('toolu_1'),
      ],
    });

    expect(
      claudeContent
        .readToolCalls(turn, new Set(['assistant-1']), now)
        .map((call) => call.toolName),
    ).toEqual(['search']);
  });
});
