import type { ToolCallRecord } from '../../shared/tracker';
import { arrayProperty, property, reactFiber, stringProperty } from '../react';
import type { ContentSite } from '../types';

const transcriptRowSelector = '[data-testid="transcript-row"]';
const turnStatusSelector = '[data-testid="TurnStatus"]';

interface RenderedMessage {
  messageId: string | null;
  content: unknown[];
  conversationId: string | null;
}

// The status row sits inside the component that renders one message; its
// props hold the message with every content block, including tool calls.
function renderedMessage(element: Element): RenderedMessage | null {
  try {
    let fiber = reactFiber(element);

    for (let depth = 0; fiber && depth < 60; depth += 1) {
      const props = property(fiber, 'memoizedProps');
      const message = property(props, 'message');
      const content = arrayProperty(message, 'content');
      if (content) {
        return {
          messageId: stringProperty(message, 'uuid'),
          content,
          conversationId: stringProperty(props, 'conversationUuid'),
        };
      }

      fiber = property(fiber, 'return');
    }
  } catch {
    return null;
  }

  return null;
}

function conversationIdFromUrl(url: URL): string | null {
  const match = url.pathname.match(/^\/chat\/([^/]+)/);
  return match?.[1] ?? null;
}

// Connector tools are named `<integration>:<tool>`.
function toolNameFrom(name: string, appName: string): string {
  const prefix = `${appName}:`;
  return name.startsWith(prefix) ? name.slice(prefix.length) : name;
}

// Only calls to MCP servers that returned a result are recorded, and only in
// messages generated by a request observed in this tab. Built-in tools such
// as web search carry no MCP server URL.
function readToolCallsFromMessage(
  { messageId, content, conversationId }: RenderedMessage,
  liveMessageIds: ReadonlySet<string>,
  now: () => Date = () => new Date(),
): ToolCallRecord[] {
  if (!messageId || !liveMessageIds.has(messageId)) {
    return [];
  }

  const resultIds = new Set(
    content
      .filter((block) => property(block, 'type') === 'tool_result')
      .map((block) => stringProperty(block, 'tool_use_id')),
  );
  const detectedAt = now().toISOString();
  const calls: ToolCallRecord[] = [];

  for (const block of content) {
    const id = stringProperty(block, 'id');
    const name = stringProperty(block, 'name');
    const appName = stringProperty(block, 'integration_name');

    if (
      property(block, 'type') !== 'tool_use' ||
      !stringProperty(block, 'mcp_server_url') ||
      !id ||
      !name ||
      !appName ||
      !resultIds.has(id)
    ) {
      continue;
    }

    calls.push({
      site: 'claude',
      id,
      conversationId:
        conversationId ?? conversationIdFromUrl(new URL(window.location.href)),
      turnId: messageId,
      appName,
      toolName: toolNameFrom(name, appName),
      toolIndex: calls.length + 1,
      detectedAt,
    });
  }

  return calls;
}

export const claudeContent: ContentSite = {
  id: 'claude',
  origin: 'https://claude.ai',
  turnSelector: transcriptRowSelector,
  readToolCalls(turn, liveIds, now) {
    return [...turn.querySelectorAll(turnStatusSelector)].flatMap((status) => {
      const rendered = renderedMessage(status);
      return rendered ? readToolCallsFromMessage(rendered, liveIds, now) : [];
    });
  },
};
